version: '3.9'

services:

   web:
      build:
         context: .
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
         - .:/usr/src/app/
      ports:
         - 8005:8000
      environment:
         - POSTGRES_NAME=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
      depends_on:
         - db

   db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data: